# Generated by Django 3.1.7 on 2021-06-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Gender', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Mobile', models.CharField(default='', max_length=30)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Branch', models.CharField(default='', max_length=30)),
                ('Semester', models.CharField(default='', max_length=30)),
                ('Regno', models.CharField(default='', max_length=30)),
                ('Place', models.CharField(default='', max_length=30)),
                ('Username', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=30)),
                ('Photo', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
