# Generated by Django 3.1.7 on 2021-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_chtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnbooktb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regno', models.CharField(default='', max_length=30)),
                ('Booktitle', models.CharField(default='', max_length=30)),
                ('Author', models.CharField(default='', max_length=30)),
                ('Returnstatus', models.CharField(default='', max_length=30)),
                ('Duedate', models.DateField()),
                ('Returndate', models.DateField()),
            ],
        ),
    ]
