# Generated by Django 3.1.7 on 2021-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_returnbooktb'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbtb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Feedback', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='issuebtb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Regno', models.CharField(default='', max_length=30)),
                ('Booktitle', models.CharField(default='', max_length=30)),
                ('Edition', models.CharField(default='', max_length=30)),
                ('Author', models.CharField(default='', max_length=30)),
                ('Publications', models.CharField(default='', max_length=30)),
                ('Date', models.CharField(default='', max_length=30)),
                ('Mobile', models.CharField(default='', max_length=30)),
                ('Photo', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
