# Generated by Django 3.1.7 on 2021-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_fbtb_issuebtb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finetb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Branch', models.CharField(default='', max_length=30)),
                ('Amount', models.PositiveIntegerField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='issuebtb',
            name='Date',
            field=models.DateField(),
        ),
    ]
