# Generated by Django 3.1.7 on 2021-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20210624_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regtable',
            name='Mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
