# Generated by Django 3.1.7 on 2021-06-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_auto_20210627_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chtable',
            name='Date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='finetb',
            name='Date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='returnbooktb',
            name='Duedate',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='returnbooktb',
            name='Returndate',
            field=models.DateField(max_length=30),
        ),
    ]
